### ISSUE TITLE
Gval not initialized.

### ISSUE THREAD

**Issue by JTrantow** [hase-berlin/pcbGcodeZprobing#1]
When I tried running this code, (Windows python 3.5.1) it had an error on line 408 as Gval wasn't initialized. I added 

```
    if match:
        Gval = int(match.group(1))
    else:
        Gval = 0
```

which seems to correct the problem.

**Comment by hase-berlin** [comment]
Line 408 in the source is
main()

Gval is not referenced there, so the "uninitialized"-error can not happen there.

GVal is referenced in line 399
if Gval == 1:

and this could indeed throw the "uninitialized" error -- but only if we are processing a line that is neither G01 nor G00.

Your suggested fix would indeed avoid this access of an uninitialized variable.
But I suggest you try another solution.

Analyse the input you processed when the error appeared.
The line that triggered the problem contains a G-code that is not processed any probably not needed for the milling.
So you can add a regular expression to the remove array (line 85, remove = [...]) that will match the line (and _not_ match lines required for the milling!). Then the line will simply be filtered out.

If the line triggering the problem must not be filtered out but passed to the output, you can add a regex to the passthrough array in line 78 and the line will be copied to the output unmodified.

The code between lines 374 and 403 is only suitable to process G01 and G00 moves.
Your suggestion forces to treat all possible inputs as G00 moves.
I strongly advise against doing this: line 386 to 396 will match those lines against regular expressions and remember extracted X and Y coordinates (in the variables X_dest and Y_dest).
This could potentially screw up the next G01 etching move if for example a line with a comment contains an X-of Y coordinate.

At least you should log a warning when you output a line that was not recognized.

Closing bug as "wontfix" because the suggested fix is potentially damaging.

hase

**Comment by JTrantow** [comment]
Ok, I was using  pcb-gcode.ulp to generate Gcode from Eagle which generates
G82 drill codes at the end of the gcode files. I picked up your script for
the probe/leveling and didn't notice the filtering features of your script.
I tried changing passthrough =["G82"] with no success. (same uninitialized
Gval message.)
Here are the offending lines:
G82 X15.2400 Y21.5900 Z-0.2794 F300.00 R3.0000 P1.000000
G82 X17.7800 Y21.5900
G82 X20.3200 Y21.5900

Are you using the Eagle Tools/Mill Outlines output as the input your python
script? My first attempt using that method failed with LinuxCNC not
understanding some of the tool codes. It looks like your script would
correct this problem?

I just tried your script with the Tools/Mill Outlines/*.ncd and everything
worked. I will try milling a board later today. Thanks for your python
script and your reply.

**Comment by hase-berlin** [comment]
Yes, I am using output from Eagle.
But I generate separate files for milling and drilling: I have to change the tool in between anyway. Actually: I generate a separate file for each drill diameter.

When milling, you should filter out the G82 moves, e.g. by adding "G82" to the remove array.

Eagle output contains some G-Codes that LinuxCNC does not understand and does complain about.
That is the reason I added the code for removing offending lines.
My standard pattern is
remove = ["%", "M48", "M71", "T\d\d", "G36 T \d", "G01.*Z-\d"]
This removes comments ("%"), M48 and M71 (no idea what they are supposed to be), tool-change (T with two digits), G36 (iirc. that is a tool diameter setting not supportes by LinuxCNC).
And I also remove the negative Z-Moves.
Eagle's milling outline generator is based on a plotter driver and was written by someone who never milled a single PCB. The Z-move is generated upward and downward with the same distance - which is stupid. So the script fixes that.

If you are running LinuxCNC, I suggest to modify your config to run the script as a filter. That way you can directly open .ncd-files from axis.
http://www.hase.net/CNC/CNC/PCB_milling.html has the detailed instructions.
(look for the FILTER section).

hase

**Comment by JTrantow** [comment]
Thank your for the explanation. That all makes sense.
